theme: jekyll-theme-minimal
title: Anian Altherr's homepage
description: Bookmark this to keep an eye on my project updates!
domain: donion74.github.io
url: https://donion74.github.io
baseurl: /docs/
